name: ${project.name}
main: net.enelson.sopcrates.SopCrates
version: ${project.version}
authors: [E_NeLsOn]
depend: [SopLib]
softdepend: [PlaceholderAPI, SopDisplays]
api-version: 1.16
commands:
  sopcrates: